import { describe, expect, test, vi } from "vitest";

import {
  CONTRACT_VERSION,
  CortexTaskSchema,
  FindingSchema,
  SetupPrEvidenceSummarySchema,
  SetupPrPreviewSchema,
  type CortexTask,
  type Finding,
  type SetupPrPreview,
} from "@control-plane/shared";

vi.mock("server-only", () => ({}));

const now = new Date("2026-06-02T09:00:00.000Z");

const cortexTask = (overrides: Partial<CortexTask> = {}): CortexTask =>
  CortexTaskSchema.parse({
    acceptanceCriteria: ["Generated setup artifacts are reviewed before merge."],
    approvalStatus: "approved",
    contractVersion: CONTRACT_VERSION,
    createdAt: now.toISOString(),
    executionMode: "setup_pr",
    externalLinks: [],
    findingIds: ["finding_1"],
    metadata: {
      sourceLabel: "setup_pr_evidence_test",
    },
    objective: "Prepare reviewer-owned setup artifacts.",
    origin: {
      type: "task_recommendation",
    },
    prArtifactIds: [],
    repoId: "github_repository_1",
    riskLevel: "medium",
    runIds: [],
    status: "approved",
    suggestedValidation: [
      {
        label: "Review validation command map",
        required: true,
        validationId: "validation-posture:review",
      },
    ],
    taskId: "cortex_task_1",
    taskRecommendationId: "task_recommendation_1",
    title: "Add validation setup",
    updatedAt: now.toISOString(),
    workspaceId: "workspace_1",
    ...overrides,
  });

const finding = (overrides: Partial<Finding> = {}): Finding =>
  FindingSchema.parse({
    category: "validation",
    confidence: 0.9,
    contractVersion: CONTRACT_VERSION,
    createdAt: now.toISOString(),
    deterministicRuleId: "validation-posture",
    evidence: [
      {
        metadata: {
          signal: "missing_policy",
        },
        paths: [".aicp/policy.json"],
        summary: "Validation setup metadata is incomplete.",
      },
    ],
    findingId: "finding_1",
    recommendation: "Create repository policy metadata for validation gates.",
    repoId: "github_repository_1",
    scanId: "repo_scan_1",
    severity: "medium",
    source: "deterministic_rule",
    status: "open",
    summary: "The repository does not expose enough validation setup metadata.",
    title: "Validation policy is missing",
    updatedAt: now.toISOString(),
    workspaceId: "workspace_1",
    ...overrides,
  });

const preview = (): SetupPrPreview =>
  SetupPrPreviewSchema.parse({
    contractVersion: CONTRACT_VERSION,
    createdAt: now.toISOString(),
    excludedTaskIds: [],
    excludedTemplateIds: [],
    files: [
      {
        omittedContent: true,
        operation: "create_or_update",
        path: ".aicp/policy.json",
        reviewInstructions: [
          "Confirm validation commands match this repository before creating the setup PR.",
        ],
        reviewRequired: true,
        sourceTaskIds: ["cortex_task_1"],
        summary: "Create or update the repository policy used by runner dry-run and safety gates.",
        templateId: "repo_policy",
      },
    ],
    metadata: {
      sourceLabel: "setup_pr_preview_service",
    },
    previewId: "setup_pr_preview_1",
    repoId: "github_repository_1",
    status: "draft",
    taskIds: ["cortex_task_1"],
    updatedAt: now.toISOString(),
    workspaceId: "workspace_1",
  });

const unsafeSerializedPattern =
  /diff --git|@@ -|process\.env|PRIVATE KEY|rawSource|sourceCode|patchText|rawOutput|Generated by Cortex setup PR template|\/Users\/rory/u;

describe("setup PR evidence summary", () => {
  test("maps generated setup files to approved tasks and safe readiness findings", async () => {
    const { buildSetupPrEvidenceSummary } = await import("./evidence");

    const summary = buildSetupPrEvidenceSummary({
      findings: [finding()],
      generatedAt: now,
      preview: preview(),
      tasks: [cortexTask()],
    });

    expect(SetupPrEvidenceSummarySchema.safeParse(summary).success).toBe(true);
    expect(summary).toMatchObject({
      findingIds: ["finding_1"],
      taskIds: ["cortex_task_1"],
    });
    expect(summary.files[0]).toMatchObject({
      findingIds: ["finding_1"],
      findings: [
        {
          category: "validation",
          findingId: "finding_1",
          severity: "medium",
          status: "open",
          title: "Validation policy is missing",
        },
      ],
      omittedContent: true,
      path: ".aicp/policy.json",
      reviewChecklist: [
        "Review .aicp/policy.json: Create or update the repository policy used by runner dry-run and safety gates.",
        "Confirm validation commands match this repository before creating the setup PR.",
      ],
      sourceTaskIds: ["cortex_task_1"],
      tasks: [
        {
          riskLevel: "medium",
          taskId: "cortex_task_1",
          title: "Add validation setup",
          validationLabels: ["Review validation command map"],
        },
      ],
      templateId: "repo_policy",
    });
    expect(summary.files[0]?.whyGenerated).toContain("1 approved setup task");
    expect(summary.files[0]?.whyGenerated).toContain("1 readiness finding");
    expect(JSON.stringify(summary)).not.toMatch(unsafeSerializedPattern);
  });
});
