import "server-only";

import {
  CONTRACT_VERSION,
  CortexTaskSchema,
  DRY_RUN_CHECKS,
  RepoPolicySchema,
  type CortexTask,
  type RepoPolicy,
} from "@control-plane/shared";

export type SetupPrTemplateId =
  | "agent_instructions"
  | "architecture_doc"
  | "backlog"
  | "ci_workflow"
  | "contributing"
  | "integration_notes"
  | "product_spec"
  | "repo_policy";

type ReviewMarkerPlacement = "file_content" | "preview_metadata";

export type SetupPrFileTemplate = {
  label: string;
  matchingValidationIds: readonly string[];
  operation: "create_or_update";
  path: string;
  reviewInstructions: readonly string[];
  reviewMarkerPlacement: ReviewMarkerPlacement;
  reviewRequired: true;
  summary: string;
  templateId: SetupPrTemplateId;
};

export type RenderedSetupPrTemplateFile = SetupPrFileTemplate & {
  content: string;
  generatedBy: "cortex_setup_pr_template";
};

const generatedMarkdownHeader = (templateId: SetupPrTemplateId): string =>
  [
    `<!-- Generated by Cortex setup PR template: ${templateId}. -->`,
    "<!-- Review required before merge. Replace placeholders and remove anything that does not fit this repository. -->",
    "",
  ].join("\n");

const renderProductSpec = (): string =>
  `${generatedMarkdownHeader("product_spec")}# Product Spec

> Review required before merge: replace bracketed notes with repository-specific product context.

## Purpose

[Describe the product purpose in one or two short paragraphs.]

## Users

- [Primary user]
- [Secondary user, if any]

## Problem

[Describe the user problem this product is meant to solve.]

## MVP Scope

- [In scope]
- [Out of scope]

## Success Criteria

- [Measurable outcome]
- [Validation signal]
`;

const renderAgentInstructions = (): string =>
  `${generatedMarkdownHeader("agent_instructions")}# AGENTS.md

## Purpose

This file guides coding agents working in this repository.

## Project Shape

- [Describe the app, packages, and major boundaries.]
- [Name the hosted coordinator surfaces and local execution surfaces, if applicable.]

## Operating Rules

- Keep changes scoped to the approved task.
- Preserve human review for consequential changes.
- Do not include credentials, private environment values, diffs, patches, or implementation excerpts in hosted metadata.

## Validation

- [List required validation commands or point to the repo policy file.]
- Record validation evidence before marking work complete.
`;

const renderArchitectureDoc = (): string =>
  `${generatedMarkdownHeader("architecture_doc")}# Architecture

## System Shape

[Describe the major runtime components and how they communicate.]

## Boundaries

- [Component or package]: [Responsibility]
- [Component or package]: [Responsibility]

## Data Flow

1. [Important flow step]
2. [Important flow step]
3. [Important flow step]

## Safety Expectations

- [Validation expectation]
- [Security or privacy expectation]
- [Review expectation]
`;

const renderBacklog = (): string =>
  `${generatedMarkdownHeader("backlog")}# Backlog

## Task Format

Each task should include:

- Identifier
- Status
- Goal
- Acceptance criteria
- Validation
- Files likely touched
- Security or trust notes

## Ready Tasks

### TASK-001 - [Task title]
Status: [ ]
Goal: [Describe the smallest valuable outcome.]
Acceptance Criteria: [Clear pass/fail criteria.]
Validation: [Required checks.]
Files Likely Touched: [Paths or ownership areas.]
Security/Trust Notes: [Any safety boundary.]
`;

const reviewPolicy: RepoPolicy = RepoPolicySchema.parse({
  allowUntrackedFiles: false,
  contractVersion: CONTRACT_VERSION,
  dryRunChecks: [...DRY_RUN_CHECKS],
  maxChangedFiles: 30,
  maxDiffLines: 800,
  protectedBranches: ["main"],
  protectedPaths: [
    ".github/workflows/**",
    ".aicp/**",
    "infra/**",
    "migrations/**",
    "apps/**/auth/**",
    "apps/**/billing/**",
  ],
  sensitivePaths: [
    ".env",
    ".env.*",
    "*.local.env",
    "*.pem",
    "*.key",
    "**/*credential*",
    "**/*secret*",
  ],
  validationCommands: [
    {
      command: "pnpm run typecheck",
      id: "typecheck",
      label: "Typecheck",
      required: true,
      timeoutSeconds: 600,
    },
    {
      command: "pnpm run lint",
      id: "lint",
      label: "Lint",
      required: true,
      timeoutSeconds: 600,
    },
    {
      command: "pnpm run format:check",
      id: "format",
      label: "Format check",
      required: true,
      timeoutSeconds: 600,
    },
    {
      command: "pnpm test",
      id: "test",
      label: "Test",
      required: true,
      timeoutSeconds: 1_200,
    },
  ],
  warningPaths: {
    auth: ["apps/**/auth/**", "packages/**/auth/**"],
    billing: ["apps/**/billing/**", "packages/**/billing/**"],
    infrastructure: [".github/workflows/**", "infra/**", "terraform/**"],
    migrations: ["migrations/**", "**/migrations/**"],
    packageLocks: ["pnpm-lock.yaml", "package-lock.json", "yarn.lock"],
  },
});

const renderRepoPolicy = (): string => `${JSON.stringify(reviewPolicy, null, 2)}\n`;

const renderCiWorkflow = (): string =>
  `# Generated by Cortex setup PR template: ci_workflow.
# Review required before merge. Confirm commands match this repository before enabling.

name: Cortex Setup Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable package manager
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Format check
        run: pnpm run format:check
      - name: Test
        run: pnpm test
`;

const renderContributing = (): string =>
  `${generatedMarkdownHeader("contributing")}# Contributing

## Review Expectations

- Keep changes small and tied to an approved task.
- Run the required validation gates before requesting review.
- Document known risks and follow-up work.

## Repository Hygiene

- Use the repository's chosen package manager consistently.
- Keep generated artifacts and local state out of version control.
- Add issue templates or task metadata when they help reviewers understand intent.
`;

const renderIntegrationNotes = (): string =>
  `${generatedMarkdownHeader("integration_notes")}# Cortex Integration Notes

## External Systems

- [System name]: [Purpose and ownership]

## Required Review

- Confirm each integration uses least-privilege access.
- Confirm no credential values are committed.
- Confirm setup steps are documented with placeholders only.
`;

const renderers = {
  agent_instructions: renderAgentInstructions,
  architecture_doc: renderArchitectureDoc,
  backlog: renderBacklog,
  ci_workflow: renderCiWorkflow,
  contributing: renderContributing,
  integration_notes: renderIntegrationNotes,
  product_spec: renderProductSpec,
  repo_policy: renderRepoPolicy,
} satisfies Record<SetupPrTemplateId, () => string>;

const setupPrFileTemplates = [
  {
    label: "Repository policy",
    matchingValidationIds: [
      "execution-risk:review",
      "security-policy-coverage:review",
      "validation-posture:review",
      "validation:lint",
      "validation:test",
      "validation:typecheck",
    ],
    operation: "create_or_update",
    path: ".aicp/policy.json",
    reviewInstructions: [
      "Confirm validation commands match this repository before creating the setup PR.",
      "Confirm protected and sensitive path rules match the repository risk profile.",
    ],
    reviewMarkerPlacement: "preview_metadata",
    reviewRequired: true,
    summary: "Create or update the repository policy used by runner dry-run and safety gates.",
    templateId: "repo_policy",
  },
  {
    label: "CI validation workflow",
    matchingValidationIds: ["ci-cd:review"],
    operation: "create_or_update",
    path: ".github/workflows/cortex-validation.yml",
    reviewInstructions: [
      "Confirm the workflow commands match this repository.",
      "Confirm branch triggers and package manager setup before merge.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create a review-required CI workflow for validation coverage.",
    templateId: "ci_workflow",
  },
  {
    label: "Agent instructions",
    matchingValidationIds: ["agent-instructions:review", "agent-readiness:review"],
    operation: "create_or_update",
    path: "AGENTS.md",
    reviewInstructions: [
      "Replace placeholders with repository-specific boundaries and validation rules.",
      "Keep instructions focused on safe AI-assisted engineering work.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create or update agent operating instructions for AI-assisted tasks.",
    templateId: "agent_instructions",
  },
  {
    label: "Architecture documentation",
    matchingValidationIds: ["architecture-docs:review"],
    operation: "create_or_update",
    path: "ARCHITECTURE.md",
    reviewInstructions: [
      "Describe runtime boundaries and responsibilities without implementation excerpts.",
      "Confirm security and validation expectations are accurate.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create architecture documentation for system boundaries and review expectations.",
    templateId: "architecture_doc",
  },
  {
    label: "AI-ready backlog",
    matchingValidationIds: ["backlog-quality:review"],
    operation: "create_or_update",
    path: "BACKLOG.md",
    reviewInstructions: [
      "Replace placeholder task content with actual approved work.",
      "Keep task metadata scoped, testable, and safe for AI-assisted execution.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create or update backlog structure for AI-ready task execution.",
    templateId: "backlog",
  },
  {
    label: "Contribution guide",
    matchingValidationIds: ["repo-hygiene:review"],
    operation: "create_or_update",
    path: "CONTRIBUTING.md",
    reviewInstructions: [
      "Confirm validation and review expectations match the repository workflow.",
      "Remove any placeholder that does not apply.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create contribution guidance for validation and review hygiene.",
    templateId: "contributing",
  },
  {
    label: "Product specification",
    matchingValidationIds: ["product-clarity:review"],
    operation: "create_or_update",
    path: "PRODUCT_SPEC.md",
    reviewInstructions: [
      "Replace placeholders with product purpose, users, scope, and success criteria.",
      "Keep the document high-level and reviewable.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create product clarity documentation for readiness scans.",
    templateId: "product_spec",
  },
  {
    label: "Integration notes",
    matchingValidationIds: ["integration:review"],
    operation: "create_or_update",
    path: "docs/CORTEX_INTEGRATIONS.md",
    reviewInstructions: [
      "Confirm integration ownership and least-privilege expectations.",
      "Use placeholders for setup values that differ by environment.",
    ],
    reviewMarkerPlacement: "file_content",
    reviewRequired: true,
    summary: "Create integration setup notes for ambiguous external-system findings.",
    templateId: "integration_notes",
  },
] as const satisfies readonly SetupPrFileTemplate[];

const templatesById = new Map(
  setupPrFileTemplates.map((template) => [template.templateId, template]),
);

export const listSetupPrFileTemplates = (): SetupPrFileTemplate[] =>
  setupPrFileTemplates.map((template) => ({
    ...template,
    matchingValidationIds: [...template.matchingValidationIds],
    reviewInstructions: [...template.reviewInstructions],
  }));

export const renderSetupPrFileTemplate = (
  templateId: SetupPrTemplateId,
): RenderedSetupPrTemplateFile => {
  const template = templatesById.get(templateId);

  if (template === undefined) {
    throw new Error(`Unknown setup PR template: ${templateId}`);
  }

  return {
    ...template,
    content: renderers[template.templateId](),
    generatedBy: "cortex_setup_pr_template",
    matchingValidationIds: [...template.matchingValidationIds],
    reviewInstructions: [...template.reviewInstructions],
  };
};

export const buildSetupPrTemplateFilesForTask = (
  input: CortexTask,
): RenderedSetupPrTemplateFile[] => {
  const task = CortexTaskSchema.parse(input);

  if (task.executionMode !== "setup_pr" || task.riskLevel === "blocked") {
    return [];
  }

  const suggestedValidationIds = new Set(
    task.suggestedValidation.map((validation) => validation.validationId),
  );

  return setupPrFileTemplates
    .filter((template) =>
      template.matchingValidationIds.some((validationId) =>
        suggestedValidationIds.has(validationId),
      ),
    )
    .map((template) => renderSetupPrFileTemplate(template.templateId));
};
